{{- if $.Values.global.tektonGitSSHKeys }}
{{- range $sshKeyName, $sshKeyValues := $.Values.global.tektonGitSSHKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "ploigos-workflow.workflowServiceAccountSecretNamePrefix" $) ($sshKeyName) | trunc -63 | trimPrefix "-" }}
  labels:
    {{- include "ploigos-workflow.labels" $ | nindent 4 }}
  annotations:
  {{- range $index, $gitURL := (index . "gitURLs") }}
    tekton.dev/git-{{ $index }}: {{ $gitURL | quote }}
  {{- end }}
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: | {{ index . "ssh-privatekey" | nindent 4 }}
  {{- if (index . "known_hosts") }}
  known_hosts: | {{ index . "known_hosts" | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
