# Based on content from: https://github.com/tektoncd/triggers/blob/main/examples/rbac.yaml

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ploigos-workflow-tekton.eventListenerServiceAccountName" . }}
  labels:
    {{- include "ploigos-workflow.labels" $ | nindent 4 }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ploigos-workflow-tekton.eventListenerServiceAccountName" . }}
rules:
# EventListeners need to be able to fetch all namespaced resources
- apiGroups: ["triggers.tekton.dev"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
# configmaps is needed for updating logging config
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["*"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["tekton-triggers"]
  verbs: ["use"]
# EventListeners need to be able to fetch any clustertriggerbindings
# NOTE: in Tekton examples this is put into a ClusterRole and ClusterBinding
#       but from testing it works fine for our use case as a namespaced Role
#       and RoleBinding and allows us to not require users to have permissions
#       to create cluster level resources.
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings", "clusterinterceptors"]
  verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ploigos-workflow-tekton.eventListenerServiceAccountName" . }}
  labels:
    {{- include "ploigos-workflow.labels" $ | nindent 4 }}
roleRef:
  kind: Role
  name: {{ include "ploigos-workflow-tekton.eventListenerServiceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "ploigos-workflow-tekton.eventListenerServiceAccountName" . }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ploigos-workflow-tekton.eventListenerServiceAccountName" . }}-cluster-resources
  labels:
    {{- include "ploigos-workflow.labels" $ | nindent 4 }}
  annotations:
    description: |
      As of Tekton Triggers v0.14.2 you need "A Kubernetes ClusterRole that permits read access to
      ClusterTriggerBindings objects".
roleRef:
  kind: ClusterRole
  name: {{ $.Values.global.eventListenerClusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "ploigos-workflow-tekton.eventListenerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
